format = """
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$docker_context\
$package\
$c\
$container\
$golang\
$helm\
$lua\
$nodejs\
$perl\
$php\
$pulumi\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$custom\
$sudo\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$status\
$shell\
$character"""
#right_format = """$time"""

[fill]
symbol=" "

[character]
success_symbol = "[%](default)"
vicmd_symbol = "[%](default)"
error_symbol = "[%](bold red)"

[git_branch]
style = "fg:dark_grey"
symbol = " "

[git_status]
style = "fg:dark_grey"

[git_state]
style = "fg:dark_grey"

[git_metrics]
added_style = "fg:dark_grey"

[directory]
style = "fg:dark_grey"
truncation_symbol = "…/"

[jobs]
symbol = "·"
style = "bold red"

[time]
disabled = false
#style = "fg:241"
style=""
format = "[$time]($style)"

[terraform]
disabled = true

[openstack]
#style = "fg:blue"
style = ""
format = 'on [$cloud]($style) '

[python]
disabled = false
format = 'via [ ($version )]($style)(($virtualenv))'
style = "fg:dark_grey"
detect_extensions = []
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

[package]
disabled = true

[java]
disabled = true

[helm]
disabled = true

[kubernetes]
style = ""
format = '[󱃾 ($cluster in) \($namespace\)]($style) '
disabled = false
detect_env_vars = ['KUBECONFIG']

[golang]
disabled = true
style = ""
format = 'via [󰟓 ($version )]($style)'

[gcloud]
disabled = true
format = 'on [$project \($account(@$domain)\)]($style) '

[docker_context]
disabled = true
style = ""

[lua]
disabled = true

[nodejs]
disabled = true

