format = """
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$docker_context\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[fill]
symbol=" "

[character]
success_symbol = "[%](default)"
vicmd_symbol = "[%](default)"
error_symbol = "[%](bold red)"

[git_branch]
symbol = " "

[directory]
truncation_symbol = "…/"

[jobs]
symbol = "·"
style = "bold red"

[time]
disabled = false
style = "fg:dark_grey"
format = "[$time]($style)"

[terraform]
disabled = true

[python]
detect_extensions = []
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

[package]
disabled = true

[java]
disabled = true

[kubernetes]
format = '[󱃾 ($cluster in) \($namespace\)](green) '
disabled = false

[golang]
format = 'via [󰟓 ($version )]($style)'
